INSERT INTO household (eircode, number_of_occupants, max_number_of_occupants, owner_occupied) VALUES
                                                                                                  ('A12 BC34', 2, 4, 1),
                                                                                                  ('B56 DE78', 3, 5, 0),
                                                                                                  ('C90 FG12', 1, 3, 1),
                                                                                                  ('D34 HI56', 4, 6, 1),
                                                                                                  ('E78 JK90', 2, 4, 0),
                                                                                                  ('F12 LM34', 3, 5, 1),
                                                                                                  ('G56 NO78', 1, 2, 0),
                                                                                                  ('H90 PQ12', 2, 4, 1),
                                                                                                  ('I34 RS56', 3, 5, 1),
                                                                                                  ('J78 TU90', 4, 6, 0),
                                                                                                  ('K12 VW34', 2, 3, 1),
                                                                                                  ('L56 XY78', 1, 2, 0),
                                                                                                  ('M90 ZA12', 3, 5, 1),
                                                                                                  ('N34 BC56', 2, 4, 1),
                                                                                                  ('O78 DE90', 4, 6, 0),
                                                                                                  ('P12 FG34', 1, 3, 1),
                                                                                                  ('Q56 HI78', 2, 4, 0),
                                                                                                  ('R90 JK12', 3, 5, 1),
                                                                                                  ('S34 LM56', 2, 4, 1),
                                                                                                  ('T78 NO90', 1, 2, 0);

INSERT INTO pets (name, animal_type, breed, age, household_eircode) VALUES
                                                                        ('Max', 'Dog', 'Labrador', 3, 'A12 BC34'),
                                                                        ('Luna', 'Cat', 'Siamese', 2, 'B56 DE78'),
                                                                        ('Charlie', 'Dog', 'Golden Retriever', 5, 'C90 FG12'),
                                                                        ('Bella', 'Cat', 'Persian', 4, 'D34 HI56'),
                                                                        ('Rocky', 'Dog', 'German Shepherd', 6, 'E78 JK90'),
                                                                        ('Lucy', 'Cat', 'Maine Coon', 3, 'F12 LM34'),
                                                                        ('Cooper', 'Dog', 'Beagle', 2, 'G56 NO78'),
                                                                        ('Milo', 'Cat', 'Ragdoll', 1, 'H90 PQ12'),
                                                                        ('Bailey', 'Dog', 'Poodle', 4, 'I34 RS56'),
                                                                        ('Loki', 'Cat', 'Scottish Fold', 2, 'J78 TU90'),
                                                                        ('Daisy', 'Dog', 'Chihuahua', 3, 'K12 VW34'),
                                                                        ('Leo', 'Cat', 'Bengal', 5, 'L56 XY78'),
                                                                        ('Buddy', 'Dog', 'Boxer', 7, 'M90 ZA12'),
                                                                        ('Nala', 'Cat', 'Sphynx', 2, 'N34 BC56'),
                                                                        ('Molly', 'Dog', 'Dachshund', 4, 'O78 DE90'),
                                                                        ('Oliver', 'Cat', 'British Shorthair', 3, 'P12 FG34'),
                                                                        ('Jack', 'Dog', 'Rottweiler', 6, 'Q56 HI78'),
                                                                        ('Simba', 'Cat', 'Abyssinian', 1, 'R90 JK12'),
                                                                        ('Coco', 'Dog', 'Shih Tzu', 5, 'S34 LM56'),
                                                                        ('Tiger', 'Cat', 'American Shorthair', 4, 'T78 NO90');
